[package]
name = "erroneous-derive"
version = "0.1.0"
authors = ["Las <las@protonmail.ch>"]

[dependencies]
matches2 = "1"
syn = "0.15.9"
quote = "0.6.8"
proc-macro2 = "0.4.20"

[lib]
path = "lib.rs"
proc-macro = true
